from __future__ import annotations

import argparse
import runpy
from pathlib import Path
from typing import Any, Iterable

import matplotlib.pyplot as plt
import numpy as np


def _component_label(component: Any, fallback_index: int) -> str:
    formula = getattr(component, "formula", None)
    state = getattr(component, "state", None)
    name = getattr(component, "name", None)

    if formula and state:
        return f"{formula}({state})"
    if formula:
        return str(formula)
    if name:
        return str(name)
    return f"species_{fallback_index + 1}"


def _build_state_labels(num_states: int, components: Iterable[Any] | None) -> tuple[list[str], bool]:
    component_list = list(components) if components is not None else []
    component_labels = [
        _component_label(component, idx) for idx, component in enumerate(component_list)
    ]

    if component_labels and num_states == len(component_labels):
        return component_labels, False
    if component_labels and num_states == len(component_labels) + 1:
        return component_labels + ["temperature"], True

    generic = [f"state_{idx + 1}" for idx in range(num_states)]
    return generic, False


def plot_batch_reactor_result(
    result: dict[str, Any],
    components: Iterable[Any] | None = None,
    save_path: Path | None = None,
    show: bool = True,
) -> None:
    if not result:
        raise ValueError("simulation_result is empty.")

    if not result.get("success", False):
        raise RuntimeError(f"Simulation failed: {result.get('message', 'unknown error')}")

    time = np.asarray(result["time"], dtype=float)
    state = np.asarray(result["state"], dtype=float)

    if state.ndim != 2:
        raise ValueError("Expected result['state'] to be a 2D array with shape (n_states, n_time).")

    labels, has_temperature_state = _build_state_labels(state.shape[0], components)

    fig, ax = plt.subplots(figsize=(10, 6))
    for idx, label in enumerate(labels):
        ax.plot(time, state[idx], linewidth=2, label=label)

    ax.set_xlabel("Time (s)")
    ax.set_ylabel("State Value")
    ax.set_title("Batch Reactor Simulation")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    if has_temperature_state:
        ax.set_ylabel("Moles / Temperature")

    plt.tight_layout()

    if save_path is not None:
        save_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(save_path, dpi=200)
        print(f"Saved plot to: {save_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def load_simulation_result(script_path: Path) -> tuple[dict[str, Any], Iterable[Any] | None]:
    try:
        namespace = runpy.run_path(str(script_path))
    except Exception as exc:
        raise RuntimeError(
            f"Could not execute simulation script '{script_path}'. "
            "Run your simulation script directly to produce `simulation_result`, "
            "or fix its imports/dependencies, then rerun this plot script with --script."
        ) from exc

    result = namespace.get("simulation_result")
    components = namespace.get("components")

    if result is None:
        raise ValueError(
            f"'simulation_result' was not found in script: {script_path}"
        )

    return result, components


def main() -> None:
    default_script = Path(__file__).resolve().parents[1] / "batch reactor" / "reaction-rate-exp-2.py"

    parser = argparse.ArgumentParser(
        description="Plot batch reactor simulation results generated by an example script."
    )
    parser.add_argument(
        "--script",
        type=Path,
        default=default_script,
        help=f"Path to the simulation script (default: {default_script})",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Optional path to save the figure (e.g., examples/plot/batch_result.png).",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open a GUI window; useful when only saving output.",
    )

    args = parser.parse_args()

    result, components = load_simulation_result(args.script)
    plot_batch_reactor_result(
        result=result,
        components=components,
        save_path=args.save,
        show=not args.no_show,
    )


if __name__ == "__main__":
    main()
