# import libs
import logging
import numpy as np
from typing import Any, Dict, List, Optional, Tuple, cast

# SECTION: total heat capacity calculation


def calc_total_heat_capacity(n: np.ndarray, cp: np.ndarray) -> float:
    """
    Calculate the total heat capacity of the system.

    Parameters
    ----------
    n : np.ndarray
        An array of molar amounts of each component.
    cp : np.ndarray
        An array of heat capacities (Cp) for each component.

    Returns
    -------
    float
        The total heat capacity of the system.
    """
    return np.sum(n * cp)


def calc_rxn_heat_generation(
        delta_h: np.ndarray,
        rates: np.ndarray,
        reactor_volume: float
) -> float:
    """
    Calculate the heat generated by reactions.

    Parameters
    ----------
    delta_h : np.ndarray
        An array of reaction enthalpies (ΔH) in J/mol for each reaction.
    rates : np.ndarray
        An array of reaction rates (r) in J/m3.s for each reaction.
    reactor_volume : float
        The volume of the reactor (V) in m3.

    Returns
    -------
    float
        The heat generated by reactions (Q_rxn) in J2/m6.mol.s.
    """
    q_rxn = 0.0
    for k in range(len(delta_h)):
        q_rxn += reactor_volume * (-delta_h[k]) * rates[k]
    return q_rxn
