# import libs
import logging
import numpy as np
from typing import Any, Dict, List, Optional, Tuple, cast

# SECTION: total heat capacity calculation


def calc_total_heat_capacity(n: np.ndarray, cp: np.ndarray) -> float:
    """
    Calculate the total heat capacity of the system.

    Parameters
    ----------
    n : np.ndarray
        An array of molar amounts of each component.
    cp : np.ndarray
        An array of heat capacities (Cp) for each component.

    Returns
    -------
    float
        The total heat capacity of the system.
    """
    return np.sum(n * cp)


def calc_rxn_heat_generation(
        delta_h: np.ndarray,
        rates: np.ndarray,
        reactor_volume: float
) -> float:
    """
    Calculate the heat generated by reactions.

    Parameters
    ----------
    delta_h : np.ndarray
        An array of reaction enthalpies (ΔH) in J/mol for each reaction.
    rates : np.ndarray
        An array of reaction rates (r) in J/m3.s for each reaction.
    reactor_volume : float
        The volume of the reactor (V) in m3.

    Returns
    -------
    float
        The heat generated by reactions (Q_rxn) in J2/m6.mol.s.
    """
    q_rxn = 0.0
    for k in range(len(delta_h)):
        q_rxn += reactor_volume * (-delta_h[k]) * rates[k]
    return q_rxn


def calc_tot_pressure_ideal(
        n_total: float,
        temperature: float,
        reactor_volume_value: float,
        R: float
) -> float:
    """
    Total pressure [Pa].
    Default: ideal gas
        P = N_total * R * T / V

    Parameters
    ----------
    n_total : float
        Total moles of gas in the reactor.
    temperature : float
        Temperature of the gas in the reactor [K].
    reactor_volume_value : float
        Volume of the reactor [m3].
    R : float
        Ideal gas constant [J/mol.K].

    Returns
    -------
    float
        Total pressure of the gas in the reactor [Pa].
    """
    # ideal gas model
    return n_total * R * temperature / float(reactor_volume_value)


def calc_dH_rxn_298(
        nu: np.ndarray,
        EnFo_IG_298: np.ndarray
):
    """
    Calculate the reaction enthalpy at 298 K (ΔH_rxn_298) for each reaction based on the stoichiometry and enthalpy of formation values.

    Parameters
    ----------
    nu : np.ndarray
        The stoichiometry matrix for the reactions, where rows correspond to components and columns correspond to reactions.
    EnFo_IG_298 : np.ndarray
        An array of enthalpy of formation values for the components at 298 K in J/mol.

    Returns
    -------
    np.ndarray
        An array of reaction enthalpies at 298 K (ΔH_rxn_298) for each reaction in J/mol.
    """
    return EnFo_IG_298 @ nu
